[phases.setup]
runtime = "python:3.9"
commands = [
  "pip install -r requirements.txt",
  "python -m nltk.downloader stopwords"
]


[phases.build]
commands = ["echo 'Build phase complete'"]

[phases.start]
commands = ["python3 model.py"]

